### ISSUE TITLE
Credit Card form won't load

### ISSUE THREAD

**Issue by tipofloe** [hps/heartland-magento2-module#25]
Hello,

I am trying to integrate the payment gateway but during checkout when I select credit card/Heartland, the page gets "whited out" and then it "freezes".  

The error message I get is:

Uncaught SyntaxError: Unexpected token < in JSON at position 2
    at JSON.parse (<anonymous>)
    at Object.success (/site/pub/static/version1492465544/frontend/theme/theme/en_US/HPS_Heartland/js/view/payment/method-renderer/heartland-method.js:75)
    at fire (jquery.js:3099)
    at Object.fireWith [as resolveWith] (jquery.js:3211)
    at done (jquery.js:9310)
    at XMLHttpRequest.callback (jquery.js:9720)

I also get an error report:

a:4:{i:0;s:306:"Warning: Cannot modify header information - headers already sent by (output started at /home/site/public_html/magentotest/app/code/HPS/Heartland/Controller/Creditcard/Get.php:64) in /home/site/public_html/magentotest/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php on line 125";i:1;s:1722:"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'Cannot modify h...', '/home/site...', 125, Array)
#1 /home/site/public_html/magentotest/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php(125): setcookie('X-Magento-Vary', '252f89d2ca7ad02...', 0, '/', '', true, true)
#2 /home/site/public_html/magentotest/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php(78): Magento\Framework\Stdlib\Cookie\PhpCookieManager->setCookie('X-Magento-Vary', '252f89d2ca7ad02...', Array)
#3 /home/site/public_html/magentotest/vendor/magento/framework/App/Response/Http.php(85): Magento\Framework\Stdlib\Cookie\PhpCookieManager->setSensitiveCookie('X-Magento-Vary', '252f89d2ca7ad02...', Object(Magento\Framework\Stdlib\Cookie\SensitiveCookieMetadata))
#4 /home/site/public_html/magentotest/vendor/magento/module-page-cache/Model/App/Response/HttpPlugin.php(25): Magento\Framework\App\Response\Http->sendVary()
#5 /home/site/public_html/magentotest/vendor/magento/framework/Interception/Interceptor.php(123): Magento\PageCache\Model\App\Response\HttpPlugin->beforeSendResponse(Object(Magento\Framework\App\Response\Http\Interceptor))
#6 /home/site/public_html/magentotest/var/generation/Magento/Framework/App/Response/Http/Interceptor.php(26): Magento\Framework\App\Response\Http\Interceptor->___callPlugins('sendResponse', Array, Array)
#7 /home/site/public_html/magentotest/vendor/magento/framework/App/Bootstrap.php(259): Magento\Framework\App\Response\Http\Interceptor->sendResponse()
#8 /home/site/public_html/magentotest/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#9 {main}";s:3:"url";s:53:"/magentotest/heartland/creditcard/get?_=1492497260251";s:11:"script_name";s:22:"/magentotest/index.php";}

I've reached out to Heartland and I've been told that I can get around the error by turning off display_errors within the PHP config.  I have verified that display_errors is turned off inside php.ini in the webroot folder.  Is there another location that I need to verify to turn this off?  I've run a search but there was only one php.ini file.  

Anyone come across this type of error message?  In any case, I would greatly appreciate if anyone could shed some light into this.  

Thank you!

**Comment by slogsdon** [comment]
Hi @tipofloe! Apologies for the inconvenience here.

We are aware of this and are working on a fix. If disabling `display_errors` isn't working, disabling error reporting for warnings should do the trick until we can get our proper fix out.
